services:

  # truth-machine:  # Idk why originally the backend container was duplicated
  #   image: bsvb/truth-machine:latest
  #   build:
  #     context: back
  #     dockerfile: Dockerfile
  #   container_name: truth-machine-backend
  #   restart: always
  #   ports:
  #     - "3030:3030"
  #   environment:
  #     NETWORK: "test"
  #     DB_NAME: "truth-machine"
  #     FUNDING_WIF: "KwEnbvYVJZrpf1HTLEb3jo9Wz19r2uzPQ2waPTPX56vfij8nd7vH"
  #     DOMAIN: "your-domain.com"
  #     CALLBACK_TOKEN: "tvhbeVfbF3nUrZTmU" # replace with your own random string
  #     MONGO_URI: "mongodb://mongo:27017"
  #     PORT: 3030

  truth-machine-demo:
    image: bsvb/truth-machine-demo:latest
    build:
      context: front
      dockerfile: Dockerfile
    container_name: truth-machine-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: https://audit-system.universalplastic.io/api

  truth-machine-backend:
    build:
      context: back
      dockerfile: Dockerfile
    container_name: truth-machine-backend
    restart: always
    ports:
      - "3030:3030"
    environment:
      NETWORK: "main"
      DB_NAME: "truth-machine"
      FUNDING_WIF: "KxeL17X2WiSLVtFrVe8ZSbcNsC487k47c4RtAvR98S4QLWGr9dda"
      DOMAIN: "https://audit-system.universalplastic.io/api"
      CALLBACK_TOKEN: "bb41f4e2424fed13d04b5a85ef7929dd0e9674a5e39f0a266802ec90acfd13f5"
      MONGO_URI: "mongodb://mongo:27017"
      PORT: 3030

  mongo:
    container_name: mongo
    image: mongo:6-jammy
    ports:
      - '28017:27017'
    volumes:
      - mongo_data:/data/db

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   command:
  #     - "http"
  #     - "http://host.docker.internal:80"
  #   environment:
  #     NGROK_AUTHTOKEN: ""
  #   ports:
  #     - 4040:4040

volumes:
  mongo_data:
