services:
  truth-machine:
    image: bsvb/truth-machine:latest
    build:
      context: back
      dockerfile: Dockerfile
    container_name: truth-machine-backend
    restart: always
    ports:
      - "3030:3030"
    environment:
      NETWORK: "test"
      DB_NAME: "truth-machine"
      FUNDING_WIF: "KwEnbvYVJZrpf1HTLEb3jo9Wz19r2uzPQ2waPTPX56vfij8nd7vH"
      DOMAIN: "your-domain.com"
      CALLBACK_TOKEN: "tvhbeVfbF3nUrZTmU" # replace with your own random string
      MONGO_URI: "mongodb://mongo:27017"
      PORT: 3030

  truth-machine-demo:
    image: bsvb/truth-machine-demo:latest
    build:
      context: front
      dockerfile: Dockerfile
    container_name: truth-machine-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_URL: truth-machine-backend:3030

  mongo:
    image: mongo:6-jammy
    ports:
      - '28017:27017'
    volumes:
      - mongo_data:/data/db

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   command:
  #     - "http"
  #     - "http://host.docker.internal:80"
  #   environment:
  #     NGROK_AUTHTOKEN: ""
  #   ports:
  #     - 4040:4040

volumes:
  mongo_data:
